name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
      # add git to the container and set it up with the token
      - name: setup git in container
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          
      # install the dependencies
      - name: install dependencies
        run: npm ci --ignore-scripts

      # run the tests
      - name: test
        run: npm test

      # check coverage - since jest-puppeteer-istanbul doesn't support it at the moment
      - name: validate coverage
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage/lcov.info
          min_coverage: 90
          token: ${{ github.token }}

      # create a badge and make a report of the coverage
      - name: display coverage
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: coverage/cobertura-coverage.xml
          BADGE_ENABLED: true
          BADGE_FILENAME: coverage-comment-badge.json
          MINIMUM_GREEN: 100
          MINIMUM_ORANGE: 90